Readme: Remove superfluous "$" in commands; add minor Python version
Wikimedia-Sverige/project-start pull request #46
Opened 2023-05-15 08:25 UTC by sebastian-berlin-wmse

The required Python version is based on what works locally. 3.7 also has EOL in about a month, so it's not really worth investigating if that still works.

2023-05-31 12:16 UTC, lokal-profil requested changes

2023-05-31 12:16 UTC, lokal-profil commented on README.md
> -`$ pip install -r requirements.txt`
The `$` was there to indicate it was a console command.

The correct way of doing that is however to use 
\`\`\`console
pip install -r requirements.txt
\`\`\`

2023-05-31 12:22 UTC, sebastian-berlin-wmse commented on README.md
> -`$ pip install -r requirements.txt`
"$" makes sense when you mix commands and output, to show which is which. I don't it servers a purpose in the cases in this file; it's clear enough that they are commands.

2023-05-31 17:17 UTC, lokal-profil approved these changes

2023-05-31 17:29 UTC, lokal-profil commented
Some of these changes were already implemented in #45

2023-06-01 09:39 UTC, sebastian-berlin-wmse commented
Closing this since I'm not that particular about the commands and the Python version is covered by #48.

2023-06-01 09:39 UTC, closed without merging

2023-06-01 09:48 UTC, sebastian-berlin-wmse commented
I saw now that the the other changes were also covered in #45.