Add Github action for running Tox on push
Wikimedia-Sverige/project-start pull request #50
Opened 2024-02-01 13:49 UTC by sebastian-berlin-wmse

Removes Isort, to avoid modifying, and fix some things the tests complained about.

Bug: T302811

2024-02-06 21:34 UTC, lokal-profil requested changes
Haven't been able to try the .github workflow but looking at the tox changes I have some concerns.

- `toxinidir` is generally used to make tox less sensitive from where it is run.
- isort: t's unclear why isort was dropped? tox only checks the code (no changes are done) and the only change required to make it pass was moving `import os` above `from time import sleep, time` in `phab.py`. Admittedly the command line was broken and a fixed version would be `isort {toxinidir}/ {posargs:-c --diff} -v --skip-gitignore`
- travis: dropping this is correct but that should also mean dropping the `.travis.yml` file

As discussed I took a look at the issue of specifying dependencies both in the `tox.ini`and in the `requirements-tests.txt`. Testing this locally tox runs fine if you comment out the deps in the individual test environments and just rely on `deps = -r requirements-test.txt` in testenv. I don't remember if this causes issues in travis (and thus may cause them in github actions) and it might make the test slower. Benefit is that your venv is aware of these and they are all collected in one spot.

[I have an updated tox.ini which I can submit as a patch or send you]

2024-02-09 08:38 UTC, sebastian-berlin-wmse commented
>   * `toxinidir` is generally used to make tox less sensitive from where it is run.
Gotcha. I think I tidied that away by accident.

>   * isort: t's unclear why isort was dropped? tox only checks the code (no changes are done) and the only change required to make it pass was moving `import os` above `from time import sleep, time` in `phab.py`. Admittedly the command line was broken and a fixed version would be `isort {toxinidir}/ {posargs:-c --diff} -v --skip-gitignore`
I think I may have happened was that I ran Isort outside of Tox and with no flags it changes files. I didn't see that `--check-only` was used. Also, I skipped `-v` because no other test gets to be verbose. If there was any particular reason to include it I can add it again.

> As discussed I took a look at the issue of specifying dependencies both in the `tox.ini`and in the `requirements-tests.txt`. Testing this locally tox runs fine if you comment out the deps in the individual test environments and just rely on `deps = -r requirements-test.txt` in testenv. I don't remember if this causes issues in travis (and thus may cause them in github actions) and it might make the test slower. Benefit is that your venv is aware of these and they are all collected in one spot.
This seems to work fine, including for Github actions. I think the extra time, which appears to only happen if you change things in tox.ini, is worth avoiding confusion for having dependencies in two places.
 
> [I have an updated tox.ini which I can submit as a patch or send you]
If there are any improvements to your version over the current one, feel free to submit it. I did the changes myself now to get a better feel for how Tox work, which I think was a good exercise either way.

2024-02-27 10:37 UTC, lokal-profil commented
> > * `toxinidir` is generally used to make tox less sensitive from where it is run.
> 
> Gotcha. I think I tidied that away by accident.
> 
> > * isort: t's unclear why isort was dropped? tox only checks the code (no changes are done) and the only change required to make it pass was moving `import os` above `from time import sleep, time` in `phab.py`. Admittedly the command line was broken and a fixed version would be `isort {toxinidir}/ {posargs:-c --diff} -v --skip-gitignore`
> 
> I think I may have happened was that I ran Isort outside of Tox and with no flags it changes files. I didn't see that `--check-only` was used. Also, I skipped `-v` because no other test gets to be verbose. If there was any particular reason to include it I can add it again.

Don't know why verbose was used but not necessary anymore
> 
> > As discussed I took a look at the issue of specifying dependencies both in the `tox.ini`and in the `requirements-tests.txt`. Testing this locally tox runs fine if you comment out the deps in the individual test environments and just rely on `deps = -r requirements-test.txt` in testenv. I don't remember if this causes issues in travis (and thus may cause them in github actions) and it might make the test slower. Benefit is that your venv is aware of these and they are all collected in one spot.
> 
> This seems to work fine, including for Github actions. I think the extra time, which appears to only happen if you change things in tox.ini, is worth avoiding confusion for having dependencies in two places.
> 
> > [I have an updated tox.ini which I can submit as a patch or send you]
> 
> If there are any improvements to your version over the current one, feel free to submit it. I did the changes myself now to get a better feel for how Tox work, which I think was a good exercise either way.

I just added `requests` to known 3rd party libraries but otherwise it looks great.

2024-02-27 10:38 UTC, lokal-profil approved these changes

2024-02-27 11:07 UTC, merged